x-env_params: &env_params
  STORAGE_DIR: /storage
  TZ: Asia/Almaty

x-default: &default
  build:
    context: .
    args:
      NEW_MAMBA_USER_ID: 1000
      NEW_MAMBA_USER_GID: 1000
  volumes:
    - ".:/project"
    - "${STORAGE_DIR}:/storage"
  shm_size: "12gb"
  working_dir: "/project"
  environment:
    <<: *env_params

services:
  server:
    <<: *default
    command: uvicorn server:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "${SERVER_PORT}:8000"
    restart: always

